/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login user
         * @description Authenticate user with name and password
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "john_doe",
                     *       "password": "secretpassword123"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                200: components["responses"]["LoginSuccess"];
                401: components["responses"]["InvalidCredentials"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new user
         * @description Create a new user account
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "john_doe",
                     *       "email": "john@example.com",
                     *       "password": "secretpassword123"
                     *     }
                     */
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                201: components["responses"]["RegisterSuccess"];
                400: components["responses"]["BadRequest"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout user
         * @description Logout current user (token remains valid until expiration)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["LogoutSuccess"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Get authenticated user's profile information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserProfile"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @description User unique identifier
             */
            id: string;
            /** @description User name */
            name: string;
            /**
             * Format: email
             * @description User email address
             */
            email: string;
        };
        LoginRequest: {
            /** @description User name */
            name: string;
            /**
             * Format: password
             * @description User password
             */
            password: string;
        };
        RegisterRequest: {
            /** @description User name (must be unique) */
            name: string;
            /**
             * Format: email
             * @description User email address (must be unique)
             */
            email: string;
            /**
             * Format: password
             * @description User password (minimum 6 characters)
             */
            password: string;
        };
        AuthResponse: {
            /** @description JWT access token */
            access_token: string;
            user: components["schemas"]["User"];
        };
        LogoutResponse: {
            /** @example Successfully logged out */
            message: string;
        };
        ErrorResponse: {
            statusCode: number;
            message: string | string[];
            error: string;
        };
    };
    responses: {
        /** @description Login successful */
        LoginSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                 *       "user": {
                 *         "id": "123e4567-e89b-12d3-a456-426614174000",
                 *         "name": "john_doe",
                 *         "email": "john@example.com"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description Invalid credentials */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "statusCode": 401,
                 *       "message": "Invalid credentials",
                 *       "error": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Registration successful */
        RegisterSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                 *       "user": {
                 *         "id": "123e4567-e89b-12d3-a456-426614174000",
                 *         "name": "john_doe",
                 *         "email": "john@example.com"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description Bad request - validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "statusCode": 400,
                 *       "message": [
                 *         "Name is required",
                 *         "Invalid email format",
                 *         "Password must be at least 6 characters"
                 *       ],
                 *       "error": "Bad Request"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict - user with this name or email already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "statusCode": 409,
                 *       "message": "User with this name already exists",
                 *       "error": "Conflict"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Logout successful */
        LogoutSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "message": "Successfully logged out"
                 *     }
                 */
                "application/json": components["schemas"]["LogoutResponse"];
            };
        };
        /** @description Unauthorized - invalid or missing token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "statusCode": 401,
                 *       "message": "Unauthorized",
                 *       "error": "Unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description User profile retrieved successfully */
        UserProfile: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "id": "123e4567-e89b-12d3-a456-426614174000",
                 *       "name": "john_doe",
                 *       "email": "john@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["User"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
