import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query"; // generated by openapi-typescript
import { ApiPaths } from "./schema";
import { APP_CONFIG } from "../config";
import { getBrowserAuthToken } from "./auth-token";

export const fetchClient = createFetchClient<ApiPaths>({
  baseUrl: APP_CONFIG.API_BASE_URL,
});
export const rqClient = createClient(fetchClient);

export const publicFetchClient = createFetchClient<ApiPaths>({
  baseUrl: APP_CONFIG.API_BASE_URL,
});
export const publicRqClient = createClient(publicFetchClient);

fetchClient.use({
  async onRequest({ request }) {
    // Current project stores token in localStorage during login/register.
    // If you later move auth to httpOnly cookies, you'll typically stop
    // sending Authorization from the browser and use a server-side proxy/BFF.
    const token = getBrowserAuthToken();
    if (token) request.headers.set("Authorization", `Bearer ${token}`);
  },
});
