import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query"; // generated by openapi-typescript
import { ApiPaths } from "./schema";
import { APP_CONFIG } from "../config";

const API_BASE_URL =
  // In the browser we go through Next.js BFF (/api/*) so the token can stay in httpOnly cookies.
  // On the server (route handlers / RSC) we can call remote backend directly.
  typeof window === "undefined" ? APP_CONFIG.API_BASE_URL : "/api";

export const fetchClient = createFetchClient<ApiPaths>({
  baseUrl: API_BASE_URL,
});
export const rqClient = createClient(fetchClient);

export const publicFetchClient = createFetchClient<ApiPaths>({
  baseUrl: API_BASE_URL,
});
export const publicRqClient = createClient(publicFetchClient);

fetchClient.use({
  async onRequest({ request }) {
    // Intentionally no Authorization header here.
    // With the BFF approach the browser calls /api/* (same-origin) and the Next.js
    // route handlers attach Authorization using httpOnly cookie.
    void request;
  },
});
